export enum TransactionCategory {
  DEPOSIT = "DEPOSIT",
  OUTWARDS = "OUTWARDS",
  WITHDRAWAL = "WITHDRAWAL",
  TRANSFER = "TRANSFER",
  REVERSAL = "REVERSAL",
  GIFTCARDS = "GIFTCARDS",
  CRYPTO = "CRYPTO",
  DATA = "DATA",
  AIRTIME = "AIRTIME",
  CABLE = "CABLE",
  SPORTS = "SPORTS",
  ELECTRICITY = "ELECTRICITY",
  EVENTS = "EVENTS",
  EDUCATION = "EDUCATION",
  CASHBACK = "CASHBACK",
  REFERRAL_BONUS = "REFERRAL_BONUS",
  CARD_CREATION = "CARD_CREATION",
  VOUCHER = "VOUCHER",
  CARD_FUNDING = "CARD_FUNDING",
}

export enum NotificationType {
  TRANSACTION = "TRANSACTION",
  WALLET = "WALLET",
  GIFTCARD = "GIFTCARD",
  DISPUTE = "DISPUTE",
  SECURITY = "SECURITY",
  PROMO = "PROMO",
  SYSTEM = "SYSTEM",
  REWARD = "REWARD",
  TICKET_PURCHASE = "TICKET_PURCHASE",
  MARKETING = "MARKETING",
}

export enum NotificationPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}
